### ISSUE TITLE
Cloudlab ESI Driver

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#280]

**Comment by tzumainn** [comment]
As a first step, we'll determine typical switch functionality and work on ensuring that the ESI CLI can handle those commands.

**Comment by tzumainn** [comment]
Based on the switch playbooks in network-runner, the common switch operations seem to be:

* set access mode vlan
  * vlan id, port name
* create vlan (no shutdown)
  * vlan id, vlan name
* delete vlan (no interface vlan)
  * vlan id
* get port conf
  * ??
* list vlans
  * ??

TRUNK OPERATIONS

* set native vlan
  * port name, vlan id
* add trunk vlan
  * vlan id, port name
* delete trunk vlan
  * vlan id, port name

NOT NEEDED AS INDIVIDUAL OPERATIONS?

* default interface config
  * port name
* config port (enable switchport, hybrid portmode, jumbo frames, rstp)
  * port name

**Comment by tzumainn** [comment]
@naved001 does the above look reasonable to you? "Not needed as individual operations" just means that I thiiiiink that there's no need for someone to run a one-line CLI command specifically to do those operations; instead, they're used by some of the operations.

**Comment by naved001** [comment]
This looks reasonable to me.

> "Not needed as individual operations" just means that I thiiiiink that there's no need for someone to run a one-line CLI command specifically to do those operations; instead, they're used by some of the operations.

Correct. Enable/Disable switchport is usually done when setting switchport to access or trunk mode. Same goes for shutting down a switchport (`shut` or `no shut`). 

hybrid portmode is just trunk port, so yeah no need to expose that as an individual operation.

jumbo frames and rstp might be nice to have in the future because when you run `default interface config` it removes any rstp or mtu setting from the switchport in addition to vlans, access mode etc. But I wouldn't worry about it for now, that's feature creep.

**Comment by tzumainn** [comment]
Okay! That's good to hear; I guess I am hoping to simply use existing OpenStack API calls, except with port names and vlans instead of ironic nodes and neutron networks, and the random operations at the bottom don't fall into any OpenStack API call. Form what you're saying it seems like we should be safe though!

**Comment by tzumainn** [comment]
Changes merged!
