### ISSUE TITLE
Track Hardware that is being added to ESI

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/esi#359]
In order to help RH keep track of the hardware that is being added to ESI we will track the hardware that is slated to be added. We can use this as a location to track other issues that are being worked on to migrate the hardware.

1. https://github.com/CCI-MOC/ops-issues/issues/35
1. https://github.com/CCI-MOC/ops-issues/issues/758
1. #340

**Comment by joachimweyl** [comment]
@naved001 do we know yet what the next set of nodes we will be adding to ESI are after the ones from HIL?

**Comment by naved001** [comment]
@joachimweyl There are still a lot of nodes from HIL that can be added to ESI once the students are done using those machines. 

Next set of nodes to add after HIL would be the Kaizen Openstack nodes, since they are a generation ahead of other HIL nodes (mostly Dell machines with Ivy Bridge Xeons). If we end up shutting off the kaizen openstack cluster before HIL nodes are free, we could start adding these nodes.

**Comment by naved001** [comment]
btw, the servers that I add from HIL to ESI, I put them in a HIL project called `migrated-to-esi` just so I can keep track of them.

**Comment by joachimweyl** [comment]
this is now being tracked in [zenhub](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTUwMjM2)
