### ISSUE TITLE
Prepare for MOC shutdown

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#410]
* are there people we should notify?
* are there configurations we should ensure are backed up (routes)?
* dates are June 5th-12th (status can be tracked [here](https://status.massopen.cloud/))

**Comment by tzumainn** [comment]
Yep! There aren't a ton of people using the MOC ESI, but I think some of them may be unaware of the coming shutdown.

**Comment by joachimweyl** [comment]
OKD folks

**Comment by joachimweyl** [comment]
Slack message sent to #okdmoca
@tzumainn are there any other ESI users you would like us to reach out to?

**Comment by naved001** [comment]
command to save switch config
```
copy running-config startup-config
```

**Comment by tzumainn** [comment]
Also would be nice to back up routes on controllers

**Comment by naved001** [comment]
@tzumainn what's the IP of the nos switch?

**Comment by naved001** [comment]
@tzumainn oh, the nos switch is the brocade 

https://github.com/CCI-MOC/esi-pilot/blob/main/ansible-deployment/switch/tasks/switches.j2#L16

Yeah, because those switches are stacked (groups of switches acting as one) they are always saving the config to memory. So, no need to explicitly save it. If they weren't stacked then that command would work.

Btw, some other switches use the command `write memory` to save the running config to startup config, but I don't think we are managing any switch that uses that.

**Comment by tzumainn** [comment]
Ah, gotcha! Okay, all three switches should be set then, thanks!

I've also written the route information to a backup file.

**Comment by joachimweyl** [comment]
@tzumainn any more steps for this issue or can this be closed now?

**Comment by tzumainn** [comment]
I'll close this - thanks!
