### ISSUE TITLE
Investigate and share details of redfish proxy

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#417]
okd is now looking into redfish proxies; they're working on one on their own, but any help may be appreciated

**Comment by tzumainn** [comment]
@samuel-zuk can you just document here what you had - I think it was a PR - and whether one might be able to reuse that work in a standalone fashion?

**Comment by samuel-zuk** [comment]
The code I wrote should work for this, it's just that currently it's strapped to the side of Ironic. I believe it would take some modification to get it running independently, as this code makes use of a bunch of internal ironic interfaces rather than sending requests to the Ironic API as the IPMI proxy code currently does, but there should be plenty of stuff to look at here:
https://review.opendev.org/c/openstack/ironic/+/845639
https://specs.openstack.org/openstack/ironic-specs/specs/not-implemented/ironic-redfish-proxy.html
https://github.com/samuel-zuk/ironic/tree/power-controls-flask

**Comment by tzumainn** [comment]
Thanks!
