### ISSUE TITLE
Figure out long-term volume provisioning solution

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#465]
There is some confusion regarding how users are supposed to use ESI's boot-from-volume capabilities. This task encompasses testing/verifying capabilities, and documenting usage.

**Comment by tzumainn** [comment]
It looks like it's difficult to use a config drive *and* boot from volume with Ironic, meaning one can't inject a ssh key. It's pretty easy to create something like a centos8-stream image with your ssh key injected, and then just use that, however.

**Comment by tzumainn** [comment]
@larsks @naved001 I'm a bit curious what you think here. I know that the volume provisioning solution for HIL/BMI was simply a bootable image with a hardcoded username/password. I think the ideal state is having a bootable image that works with config drive and allows a user to inject an SSH key. However, from my Ironic testing (followed by an examination of the code), that's simply not possible right now.

Another alternative is to simply ask users to create their own custom image; after Lars shared his script for creating a bootable centos8 image, I realized it was pretty trivial to simply add one's ssh key there. Users can then upload that image to glance, and continue with the workflow.

Do you guys think that putting this on the user is a reasonable solution? Or is there something I might be missing?

**Comment by larsks** [comment]
@tzumainn I think that pushing this to the user is problematic. By requiring hardcoded credentials in an image, we make it impossible to share images. Rather than having a library of common images, every person working with ESI will need to build custom images. Depending on their local operating system and level of familiarity with the process, this may be a substantial barrier. This means that we'll see groups building images with shared credentials (either ssh keys or a hardcoded username/password), which is a security concern.

Maybe this is how we start, but ideally we come up with a solution to this problem. It's worth noting that we don't necessarily need config **drive** support; cloud-init is also able to use network data sources. The trick here is authenticating access to the metadata service; in the regular nova + neutron world, this is handled via a proxy service (started by neutron) that injects identifying headers into http requests [1].

I don't know how much effort would be involved here, but I agree that it's not critical right now.

[1]: https://github.com/openstack/neutron/blob/f90d7d2a9e49688f7baee13268c3ba34f59d5a16/neutron/agent/l2/extensions/metadata/host_metadata_proxy.py

**Comment by tzumainn** [comment]
Okay - I'm going to move this issue into the backlog then, since I think the desired solution is fairly non-trivial. The normal Ironic way of accomplishing this is through a config drive created as a partition on the node (and which can be specified from the command line; however, I think (?) that boot-from-volume creates an issue here since the node doesn't boot from its own disk where that partition can be found. I looked briefly at the nova + neutron world, and the issue there is that it requires nova, which we don't currently install.

**Comment by joachimweyl** [comment]
no longer planning to support volume provisioning.
