### ISSUE TITLE
Migrate ESI from MOC Keycloak to NERC Keycloak

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/esi#494]
## Motivation
Having one Keycloak for all tools NERC is using will be beneficial. MOC no longer needs to maintain its own Keycloak.

## Completion Criteria
ESI authenticating with NERC Keycloak.

## Description
- [ ] Disconnect ESI from MOC Keycloak
- [ ] Connect ESI to NERC Keycloak
- [ ] Test

## Completion dates
Desired - 2024-01-24
Required - TBD

**Comment by joachimweyl** [comment]
@tzumainn how many users currently use Keycloak for ESI. If you have more than 20 users please work with @knikolla to create a script to migrate users. Otherwise please let users know they will need to create a new Keycloak login.
@jtriley, please provide @tzumainn the URL needed to transition to the NERC Keycloak

**Comment by tzumainn** [comment]
@joachimweyl this would be on the new MOC ESI, so there would be no migration needed. I believe @naved001 is handling the configuration in the new MOC ESI.

**Comment by joachimweyl** [comment]
@tzumainn while @naved001 is away for 2 weeks is this something you have access to updating or is this something only he has access to?

**Comment by tzumainn** [comment]
Ah - I think I might be able to do it, but I'm not entirely familiar with the required mechanics (although I think I could get @DanNiESh to help). However, no one is currently live on the new MOC ESI, so is this a big priority at the moment?

**Comment by DanNiESh** [comment]
> Ah - I think I might be able to do it, but I'm not entirely familiar with the required mechanics (although I think I could get @DanNiESh to help). However, no one is currently live on the new MOC ESI, so is this a big priority at the moment?

I don't actually have NERC keycloak credentials or admin access. I think @knikolla could help to create a OIDCClient for esi and give us the idp endpoint.

**Comment by knikolla** [comment]
> I don't actually have NERC keycloak credentials or admin access. I think @knikolla could help to create a client for new moc esi and give us the idp endpoint.

I do have admin access, but I'd prefer this be something @jtriley does since I defer changes to production systems to him.

**Comment by joachimweyl** [comment]
@tzumainn my understanding was that this was a small change and would not slow down other work. If this is going to block other work then we can wait for @naved001 to return for the ESI side of things.
@jtriley Am I correct that providing the IDP endpoint is a small task?

**Comment by tzumainn** [comment]
@joachimweyl Oh, I've just never done it. I'm also pretty sure this is a small task, but if something goes wrong I'll end up poking at random people with questions!

**Comment by naved001** [comment]
This is done.

The file at `/var/lib/config-data/puppet-generated/keystone/etc/httpd/conf.d` was updated on 3 controllers with configuration from NERC keycloak. The keystone container was restarted, and then the openstack identity provider was updated `openstack identity provider set --remote-id https://keycloak.mss.mghpcc.org/auth/realms/mss moc`

The keycloak secrets are in vault (https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/keycloak%2Fclients%2Fesi/details?version=1)

We ran into an issue because I messed up the SELinux context of the conf file which I fixed with `chcon -t container_file_t 10-keystone_wsgi.conf`  and then the keystone container started successfully.
