### ISSUE TITLE
Investigate failure of esi-leap CLI if no internal keystone endpoint

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#86]
esi leap CLI commands fail, but other cli commands, such as glance or cinder, succeed.

**Comment by tzumainn** [comment]
I just tested this, and my 'openstack esi *' commands work even without an internal keystone endpoint. @samuel-zuk I'll leave this open for a bit if you want to test it on your end some more so we can figure out what's going on - but I'm also fine just closing this issue.

**Comment by samuel-zuk** [comment]
My guess is that it was actually due to me not having the [keystone] section in my esi-leap.conf file, rather than the absence of the internal keystone endpoint. At some point I'll test this theory on a fresh install. One thing I do remember however, is esi leap CLI commands failing and returning only `faultstring`, which could probably be handled more gracefully... once we figure out exactly what the problem I was running into was.

**Comment by tzumainn** [comment]
It's possible that faultstring issue is fixed now; I vaguely remember running into that myself, and pushing a PR to fix it. Anyway, it sounds like this issue can be closed for now, and we can re-open if we need to re-evaluate.
