### ISSUE TITLE
Plan and implement additional test cases

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#93]
* "owner changes" have changed to subleases
* additional investigation?

**Comment by tzumainn** [comment]
@hpdempsey has resolved the owner change debate; I'll update https://docs.google.com/document/d/1CL9hvYWLxYDH6To92gIDnLfPGn3UIcaxOWj4lfDmLAA/edit# to reflect those changes and then we should be able to do another pass over the test cases based on that implementation document.

**Comment by samuel-zuk** [comment]
I've realized that for the most part, planning and implementing new test cases and refactoring the old ones are very intertwined problems due to how different the testing workflow is after migrating from shell scripts -> python. I will close #92 once all the cases that the shell scripts tested are refactored, but at the moment that's downstream from figuring out how to restructure the functional tests in a forward-thinking way.

**Comment by samuel-zuk** [comment]
Here's a WIP document (includes a copy of the old esi test case doc) that I'm currently using to brainstorm how to structure these tests & what exactly to test for: https://docs.google.com/spreadsheets/d/1_oAIg50CNqGg51nZCGpUgzn5D-cVDjAwzERTAuAE6cE/edit#gid=2135922655
